CREATE TABLE USER (
    ID INT NOT NULL AUTO_INCREMENT,
    NICKNAME VARChAR(45) NOT NULL UNIQUE,
    PASSWORD VARCHAR(90) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL UNIQUE,
    PICTURE VARCHAR(45),
    USER_ROLE_ID INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(USER_ROLE_ID) REFERENCES USER_ROLE(ID)
);